// Generated by CoffeeScript 1.9.3
(function() {
  var getTimerValue, interval, timer;

  timer = $('#baldwin-timer-value')[0];

  getTimerValue = function() {
    return timer.getAttribute('data-seconds-left');
  };

  interval = setInterval((function() {
    if (getTimerValue() <= 0) {
      document.title = 'DONE!';
      return cancelInterval(interval);
    }
  }), 10000);

}).call(this);
