// Generated by CoffeeScript 1.9.3
var HUMAN_TIMEOUT_MAX, HUMAN_TIMEOUT_MIN, LOADING_WAIT, humanTimeout, sell;

HUMAN_TIMEOUT_MIN = 100;

HUMAN_TIMEOUT_MAX = 1000;

LOADING_WAIT = 1000;

humanTimeout = function(f, extraWait) {
  if (extraWait == null) {
    extraWait = 0;
  }
  return setTimeout(f, randInt(HUMAN_TIMEOUT_MIN + extraWait, HUMAN_TIMEOUT_MAX + extraWait));
};

sell = function(id, nListings, price, quantity) {
  var itemInList;
  if (quantity == null) {
    quantity = 1;
  }
  if (nListings <= 0) {
    return;
  }
  itemInList = findMatches("a[rel][onclick*='\\'" + id + "\\'']", 1, 1);
  itemInList = $(itemInList[itemInList.length - 1]);
  itemInList.click();
  return setTimeout((function() {
    var durationDropdown, gemRadio, postAuctionButton, quantityDropdown, treasurePrice, treasureRadio;
    quantityDropdown = findMatches('select[name=qty]', 1, 1);
    durationDropdown = findMatches('select[name=drtn]', 1, 1);
    treasurePrice = findMatches('input[name=treas]', 1, 1);
    treasureRadio = findMatches('input[type=radio][name=cur][value=t]', 1, 1);
    gemRadio = findMatches('input[type=radio][name=cur][value=g]', 1, 1);
    postAuctionButton = findMatches('input[type=submit][value="Post Auction"]', 1, 1);
    treasureRadio.click();
    treasurePrice.val(price.toString());
    quantityDropdown.val(quantity.toString());
    durationDropdown.val(3);
    return humanTimeout((function() {
      postAuctionButton.click();
      return humanTimeout((function() {
        findMatches('button#yes', 1, 1).click();
        return humanTimeout((function() {
          findMatches('button#yes', 1, 1).click();
          return setTimeout((function() {
            return sell(id, nListings - 1, price, quantity);
          }), LOADING_WAIT);
        }), LOADING_WAIT);
      }), LOADING_WAIT);
    }), LOADING_WAIT);
  }), LOADING_WAIT);
};
