// Generated by CoffeeScript 1.9.3
var FormData, GEMS, TREASURE, browseAllBackup, button, form,
  slice = [].slice;

TREASURE = 0;

GEMS = 1;

FormData = (function() {
  function FormData(form1) {
    this.form = form1;
  }

  FormData.prototype.field = function(name, newValue) {
    var field;
    field = this.form.find("[name=" + name + "]");
    if (newValue) {
      return field.val(newValue);
    } else {
      return field.val();
    }
  };

  return FormData;

})();

form = new FormData(findMatches('form#searching', 1, 1));

browseAllBackup = window.browseAll = function() {
  var args, cat, filledFields, gh, ghl, gl, gll, i, j, k, len, m, name, postData, ref, ref1, ref2, tab, th, thl, tl, tll;
  args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
  console.log.apply(console, ['browseAll called with'].concat(slice.call(args)));
  postData = {};
  postData.tab = args[0], postData.page = args[1], j = args.length - 2, postData.ordering = args[j++], postData.direct = args[j++];
  if (postData.page == null) {
    m = findMatches('#ah_left > div:nth-child(3) > span', 0, 1);
    if (m.length) {
      postData.page = m.text();
    } else {
      console.log('No page element found, assuming only 1 page.');
      postData.page = '1';
    }
  }
  if (postData.tab == null) {
    if ((tab = /[?&]tab=([^&]+)/.exec(window.location.href)) != null) {
      postData.tab = tab[1];
    } else {
      postData.tab = 'food';
    }
    if ((ref = !postData.tab) === 'food' || ref === 'mats' || ref === 'app' || ref === 'dragons' || ref === 'fam' || ref === 'battle' || ref === 'skins' || ref === 'other') {
      throw new Error("Detected tab as invalid option " + (postData.tab.toString()) + ".");
    }
  }
  if (postData.ordering == null) {
    if ($('img[src*="button_expiration_active.png"]').length) {
      postData.ordering = 'expiration';
    } else if ($('img[src*="button_price_active.png"]').length) {
      postData.ordering = 'cost';
    } else {
      throw new Error("Couldn't detect ordering (expiration or price).");
    }
  }
  if (postData.direct == null) {
    if ($('img[src*="button_ascending_active.png"]').length) {
      postData.direct = 'ASC';
    } else if ($('img[src*="button_descending_active.png"]').length) {
      postData.direct = 'DESC';
    } else {
      throw new Error("Couldn't detect sorting direction.");
    }
  }
  if ((cat = form.field('cat')).length) {
    postData.cat = cat;
  } else if ((name = form.field('name')).length) {
    postData.name = name;
  }
  tl = form.field('tl');
  th = form.field('th');
  gl = form.field('gl');
  gh = form.field('gh');
  ref1 = [tl.length, th.length, gl.length, gh.length], tll = ref1[0], thl = ref1[1], gll = ref1[2], ghl = ref1[3];
  filledFields = 0;
  ref2 = [tll, thl, gll, ghl];
  for (k = 0, len = ref2.length; k < len; k++) {
    i = ref2[k];
    if (i) {
      filledFields += 1;
    }
  }
  if (tll || thl) {
    if (tll) {
      postData.tl = tl;
    }
    if (thl) {
      postData.th = th;
    }
  } else if (gll || ghl) {
    if (gll) {
      postData.gl = gl;
    }
    if (ghl) {
      postData.gh = gh;
    }
  }
  console.log('Posting', postData);
  return $.ajax({
    type: "POST",
    data: postData,
    url: "includes/ah_buy_" + postData.tab + ".php",
    cache: false
  }).done(function(stuff) {
    findMatches("#ah_left", 1, 1).html(stuff);
    return setTimeout((function() {
      return window.browseAll = browseAllBackup;
    }), 20);
  });
};

button = findMatches('input#go', 1, 1);

button.attr('type', 'button');

button.click(function() {
  return browseAllBackup();
});
