// Generated by CoffeeScript 1.9.3
var CLICK_TIMEOUT_MAX, CLICK_TIMEOUT_MIN, bondButton;

CLICK_TIMEOUT_MIN = 300;

CLICK_TIMEOUT_MAX = 1000;

if ((bondButton = findMatches('img[src*="button_bond.png"]', 0, 1)).length) {
  setTimeout((function() {
    return bondButton.click();
  }), randInt(CLICK_TIMEOUT_MIN, CLICK_TIMEOUT_MAX));
}
